### ISSUE TITLE
Failed to initialize DaikinApi after HA update

### ISSUE THREAD

**Issue by Marc1979** [rospogrigio/daikin_residential#142] opened 2023-06-01 10:25 UTC
After updating to:
Home Assistant 2023.6.0b1
Supervisor 2023.05.0
Operating System 10.2
Frontend-versie: 20230601.0 - latest

I get the following error message and the intergration is not loaded

Logger: custom_components.daikin_residential.config_flow
Source: custom_components/daikin_residential/config_flow.py:72
Integration: Daikin Residential Controller ([documentation](https://github.com/rospogrigio/daikin_residential/), [issues](https://github.com/rospogrigio/daikin_residential/issues))
First occurred: 12:22:18 (1 occurrences)
Last logged: 12:22:18

Failed to initialize DaikinApi: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).

**Comment by rospogrigio** [comment] 2023-06-01 10:35
This was fixed with latest release of the integration (2.3.1). Update and restart HA.
Please use the search function before posting, in the future.
Closing as duplicate of #140 .

**Closed by rospogrigio** 2023-06-01 10:35 UTC
