### ISSUE TITLE
No longer work under Homeassistant 2023.6.0

### ISSUE THREAD

**Issue by frli4797** [rospogrigio/daikin_residential#144] opened 2023-06-08 08:06 UTC
**No longer work under Homeassistant 2023.6.0**

Since installing 2023.6.0 this plugin no longer loads at all. 

**Log**
```Error setting up entry Daikin for daikin_residential
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/__init__.py", line 84, in async_setup_entry
    daikin_api = DaikinApi(hass, entry)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/daikin_api.py", line 54, in __init__
    self.openIdClient = Client(client_id=self.openIdClientId, config=configuration)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/oic/__init__.py", line 354, in __init__
    self.settings = settings or OicClientSettings()
                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 96, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 51, in __init__
    self.client_cert = client_cert
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 73, in __setattr__
    raise SettingsException(
oic.utils.settings.SettingsException: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).```

**Comment by rospogrigio** [comment] 2023-06-08 08:14
This was fixed with latest release of the integration (2.3.1). Update and restart HA.
Please use the search function before posting, in the future.
Closing as duplicate of https://github.com/rospogrigio/daikin_residential/issues/140 .

**Closed by rospogrigio** 2023-06-08 08:14 UTC

**Comment by frli4797** [comment] 2023-06-08 08:36
Sorry 'bout that. Thanks for fixing.
