### ISSUE TITLE
[Issue]: Intergration fails to launch agter 2023.6.1 update - Failed to set up

### ISSUE THREAD

**Issue by vytiskk** [rospogrigio/daikin_residential#151] opened 2023-06-12 08:43 UTC
File "/config/custom_components/daikin_residential/__init__.py", line 84, in async_setup_entry
daikin_api = DaikinApi(hass, entry)
^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/daikin_residential/daikin_api.py", line 54, in __init__
self.openIdClient = Client(client_id=self.openIdClientId, config=configuration)

Any help would be much apprecaited

**Comment by jwillemsen** [comment] 2023-06-12 08:43
Duplicate of https://github.com/rospogrigio/daikin_residential/issues/140

**Comment by rospogrigio** [comment] 2023-06-12 08:45
This was fixed with latest release of the integration (2.3.1). Update and restart HA.
Please use the search function before posting, in the future.
Closing as duplicate of https://github.com/rospogrigio/daikin_residential/issues/140 .

**Closed by rospogrigio** 2023-06-12 08:45 UTC
