### ISSUE TITLE
Error: Failed to retrieve access token set

### ISSUE THREAD

**Issue by jdserras** [rospogrigio/daikin_residential#19] opened 2021-09-28 17:53 UTC
I did install the add-on using HACS without issues but when trying to add the integration by typing email and password I get this error after a couple of minutes trying: "Failed to retrieve access token set.

Here is the log info:

2021-09-28 18:38:36 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] Initialing Daikin Residential API...
2021-09-28 18:38:36 INFO (MainThread) [custom_components.daikin_residential.daikin_api] Daikin Residential API initialized.
2021-09-28 18:38:36 INFO (MainThread) [custom_components.daikin_residential.daikin_api] Retrieving new TokenSet...
2021-09-28 18:39:07 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] STATE: sWs8kP3o6ns8Fh636UzVJH_Q52hz7ZnvTfVMIV4OJJk
2021-09-28 18:39:23 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] SAMLCONTEXT: eu1_964626835798_c0b04e0c-d6cd-403e-9564-828f46b653cb
2021-09-28 18:39:24 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] VERSION: 12426-3-27214170
2021-09-28 18:39:24 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] LOGIN REPLY: {'callId': '661584e82ea14241a8f18201bee59210', 'errorCode': 0, 'apiVersion': 2, 'statusCode': 200, 'statusReason': 'OK', 'time': '2021-09-28T17:39:24.577Z', 'registeredTimestamp': 1622468400, 'UID': 'd843c9a581144730904277bdef89fdc3', 'UIDSignature': 'gLbNUrh0nXDp4IAkT41BCjCqKqc=', 'signatureTimestamp': '1632850764', 'created': '2021-05-31T13:39:23.178Z', 'createdTimestamp': 1622468363, 'isActive': True, 'isRegistered': True, 'isVerified': True, 'lastLogin': '2021-09-28T17:39:24.547Z', 'lastLoginTimestamp': 1632850764, 'lastUpdated': '2021-05-31T13:40:11.813Z', 'lastUpdatedTimestamp': 1622468411813, 'loginProvider': 'site', 'oldestDataUpdated': '2021-05-31T13:39:23.178Z', 'oldestDataUpdatedTimestamp': 1622468363178, 'profile': {'firstName': 'João', 'lastName': 'Serrasqueiro', 'country': 'PT', 'email': 'jdm***********@gmail.com'}, 'registered': '2021-05-31T13:40:00.218Z', 'socialProviders': 'site', 'verified': '2021-05-31T13:40:11.813Z', 'verifiedTimestamp': 1622468411813, 'newUser': False, 'sessionInfo': {'login_token': 'st2.s.AcbH_PHG5g.00yBU81kU7CM9oqJUI-AXaPTntf57tEZ9hBTNB187SbDoifb6hmMM0JfvmQYy2z8c0wmOjPY-OiZ_KL9gom6WqLGlhsPW8XKpSDX1jid8JU.qrF5Za0Ja16_pA_Wa5oU04bArZxEf1jPbYNCP3qydEAAPuoPAvftQklHVP2yy4Heit1JyMhwXB0myvEM1LD_yg.sc3', 'expires_in': '31536000'}}
2021-09-28 18:43:28 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] VERIFIER: -Fvq4~_JXx1olR6jPSjq9T4aaX47KEJv8R-4.s_DrWpsI8VDd9dq49hs4qBAEH37
2021-09-28 18:43:28 ERROR (MainThread) [custom_components.daikin_residential.config_flow] Failed to retrieve Access Token: ('Failed to retrieve access token: %s', KeyError('code'))
2021-09-28 18:43:28 ERROR (MainThread) [aiohttp.server] Error handling request`

**Comment by rospogrigio** [comment] 2021-09-29 08:12
Mmm, this is weird. It looks like the login is successful but then something goes wrong after that. There are some commented `_LOGGER.debug` lines after the login part (line 383 and following), try to uncomment those and post what they print, maybe we can figure out what's going on...

**Comment by jdserras** [comment] 2021-09-29 10:03
When installing from HACS, the folder TOOLS isn´t copied. Is that necessary?

**Comment by rospogrigio** [comment] 2021-09-29 10:13
No, that contains just some tools to test and debug. Actually, another good attempt you could perform is launch the tokensaver.py script you find there and see if it succeeds: it could be a good starting point to try to debug this.

**Comment by jdserras** [comment] 2021-09-29 10:25
Here is the new debug:

2021-09-29 11:13:14 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] Initialing Daikin Residential API...
2021-09-29 11:13:14 INFO (MainThread) [custom_components.daikin_residential.daikin_api] Daikin Residential API initialized.
2021-09-29 11:13:14 INFO (MainThread) [custom_components.daikin_residential.daikin_api] Retrieving new TokenSet...
2021-09-29 11:13:44 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] STATE: PteDRdldEHJc70odlO8NL3461tO9g94VxlxQToq4FkQ
2021-09-29 11:14:10 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] SAMLCONTEXT: eu1_964626835798_614f9c55-9d15-4f0f-8c52-a5ab706c4bdd
2021-09-29 11:14:20 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] VERSION: 12426-3-27215130
2021-09-29 11:14:29 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] LOGIN REPLY: {'callId': 'e304b0d22a254f5f92c797e3c9c6bb44', 'errorCode': 0, 'apiVersion': 2, 'statusCode': 200, 'statusReason': 'OK', 'time': '2021-09-29T10:14:28.206Z', 'registeredTimestamp': 1622468400, 'UID': 'd843c9a581144730904277bdef89fdc3', 'UIDSignature': 'j6DUeBJiOE1UY/IW5WNHt0AdCus=', 'signatureTimestamp': '1632910468', 'created': '2021-05-31T13:39:23.178Z', 'createdTimestamp': 1622468363, 'isActive': True, 'isRegistered': True, 'isVerified': True, 'lastLogin': '2021-09-29T10:14:28.170Z', 'lastLoginTimestamp': 1632910468, 'lastUpdated': '2021-05-31T13:40:11.813Z', 'lastUpdatedTimestamp': 1622468411813, 'loginProvider': 'site', 'oldestDataUpdated': '2021-05-31T13:39:23.178Z', 'oldestDataUpdatedTimestamp': 1622468363178, 'profile': {'firstName': 'João', 'lastName': 'Serrasqueiro', 'country': 'PT', 'email': 'jdm**********@gmail.com'}, 'registered': '2021-05-31T13:40:00.218Z', 'socialProviders': 'site', 'verified': '2021-05-31T13:40:11.813Z', 'verifiedTimestamp': 1622468411813, 'newUser': False, 'sessionInfo': {'login_token': 'st2.s.AcbHGzkwug.bRIH1S0Pp4NE_xZgqWL7JW9c5WpToTM-nlj2MTZhvv58g-WpPLx0CsfjDM9tgBhJt01fgyOibiuNDu3VCgBXeT8xE1bk1iwZNaYuQxIMCvw.MAo0gli3ReM0kiLKdhcHdFZGN-XJeRR8Qnj02w18-HpLP7ergCu_c1FlfvWms6ntoTtZeygExco8NXM_rm1f2A.sc3', 'expires_in': '31536000'}}
2021-09-29 11:21:07 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] VERIFIER: 5imgmQPlVD08iaSzFOPTJuRoz01~bLyRiYICGPM5CVFd8A8b1WrUG04RGOxo8Ud8
2021-09-29 11:21:07 ERROR (MainThread) [custom_components.daikin_residential.config_flow] Failed to retrieve Access Token: ('Failed to retrieve access token: %s', KeyError('code'))

**Comment by rospogrigio** [comment] 2021-09-29 10:26
Can you try to use the tokensaver.py script and see what happens?

**Comment by jdserras** [comment] 2021-09-29 10:26
You mean copy the file?

**Comment by rospogrigio** [comment] 2021-09-29 10:28
I mean download the script and launch it like this: `./tokensaver.py [email] [password]` .

**Comment by jdserras** [comment] 2021-09-29 10:29
Download to daikin_residential folder in custom_components?

**Comment by rospogrigio** [comment] 2021-09-29 10:33
Download it wherever and launch it

**Comment by jdserras** [comment] 2021-09-29 10:37
Sorry for this beginner questions, but where can I launch it, using Terminal & SSH add-on for example?

**Comment by jdserras** [comment] 2021-09-29 11:02
I tried and I found this:

![image](https://user-images.githubusercontent.com/77854423/135256307-21588114-e9e3-4ab0-b1b7-55e14d6922f5.png)

**Comment by rospogrigio** [comment] 2021-09-29 11:05
Launch it with python3, and in case it still fails launch `pip3 install requests` to install the required module.

**Comment by jdserras** [comment] 2021-09-29 11:14
No I get this:

![image](https://user-images.githubusercontent.com/77854423/135257868-4b892282-a0a1-4e2e-a403-8b1ec8cb3016.png)

**Comment by rospogrigio** [comment] 2021-09-29 11:16
Now it's `pip3 install oic` . Alternatively, if you feel fine with it of course, you could send me your credentials privately and I can test it myself, then you can just change your password when I've finished testing, think about this.

**Comment by jdserras** [comment] 2021-09-29 11:18
Here is the result:

![image](https://user-images.githubusercontent.com/77854423/135258460-6ee9624f-b194-4afa-9e9b-9850b3c40577.png)

**Comment by rospogrigio** [comment] 2021-09-29 11:23
Weird, can you try with the email and password within quotes? Like tokensaver "email" "password" ?

**Comment by jdserras** [comment] 2021-09-29 11:26
With quotes works:

![image](https://user-images.githubusercontent.com/77854423/135259522-e9a93913-b9f3-43d7-8d49-86199bfd2c3d.png)

**Comment by jdserras** [comment] 2021-09-29 11:27
But in HA I already tried to type the email and passwor within quotes, in the form that appears during the integration, and didn´t work.

**Comment by rospogrigio** [comment] 2021-09-29 11:29
Well ok, then at least we know it potentially works. Now you should try to figure out what's going wrong by comparing the debug output of the tokensaver with what you get in HA logs: if you compare the tokensaver.py and the daikin_api.py sources you'll see that they are basically running the same code to retrieve the token.

**Comment by jdserras** [comment] 2021-09-29 12:22
Now I tried to launch the script in the same laptop where the HA is installed and I get this, wihtout find any device:

![image](https://user-images.githubusercontent.com/77854423/135267445-cf727eb3-b78c-40bf-b50e-f10860f322fb.png)

**Comment by rospogrigio** [comment] 2021-09-29 12:25
Looks like you have a time mismatch (it says the token was issued in the future), are you sure your system time is correct?

**Comment by jdserras** [comment] 2021-09-29 12:33
I did the reboot of PC, after installing python3 and worked. but in HA the problem remains

**Comment by rospogrigio** [comment] 2021-09-29 12:36
I believe the problem is there, maybe there is some time mismatch in your system. You could also try to add the following lines to configuration.yaml:
```
    homeassistant.config: debug
    homeassistant.config_entries: debug
```
and see if you get more debug info.

**Comment by jdserras** [comment] 2021-09-29 13:17
Ok, now I got this as log info:

2021-09-29 14:04:34 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] Initialing Daikin Residential API...
2021-09-29 14:04:34 INFO (MainThread) [custom_components.daikin_residential.daikin_api] Daikin Residential API initialized.
2021-09-29 14:04:34 INFO (MainThread) [custom_components.daikin_residential.daikin_api] Retrieving new TokenSet...
2021-09-29 14:04:42 DEBUG (MainThread) [homeassistant.config_entries] Config entry 'FiberGateway GR241AG' for upnp integration not ready yet; Retrying in 40 seconds
2021-09-29 14:05:04 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] STATE: jhWpD3-FQnUaSfk2Ovz7m6I4ct6DhQNphGg1mKk1ImA
2021-09-29 14:05:20 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] SAMLCONTEXT: eu1_964626835798_93cc8f52-26e8-4953-88be-8c1ebe6e5ad6
2021-09-29 14:05:21 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] VERSION: 12426-3-27215310
2021-09-29 14:05:21 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] LOGIN REPLY: {'callId': '664d64c1f3044f38a0e1d38996b6d045', 'errorCode': 0, 'apiVersion': 2, 'statusCode': 200, 'statusReason': 'OK', 'time': '2021-09-29T13:05:21.745Z', 'registeredTimestamp': 1622468400, 'UID': 'd843c9a581144730904277bdef89fdc3', 'UIDSignature': 'ZiGivkllZeugtGnZUuH9nUJE4hU=', 'signatureTimestamp': '1632920721', 'created': '2021-05-31T13:39:23.178Z', 'createdTimestamp': 1622468363, 'isActive': True, 'isRegistered': True, 'isVerified': True, 'lastLogin': '2021-09-29T13:05:21.704Z', 'lastLoginTimestamp': 1632920721, 'lastUpdated': '2021-05-31T13:40:11.813Z', 'lastUpdatedTimestamp': 1622468411813, 'loginProvider': 'site', 'oldestDataUpdated': '2021-05-31T13:39:23.178Z', 'oldestDataUpdatedTimestamp': 1622468363178, 'profile': {'firstName': 'João', 'lastName': 'Serrasqueiro', 'country': 'PT', 'email': 'jdmserrasqueiro@gmail.com'}, 'registered': '2021-05-31T13:40:00.218Z', 'socialProviders': 'site', 'verified': '2021-05-31T13:40:11.813Z', 'verifiedTimestamp': 1622468411813, 'newUser': False, 'sessionInfo': {'login_token': 'st2.s.AcbHOPoeNg.PCdj6JHwm47Hf3QryoOE2KbAWa-Ke1jIxS0ZKV7BAQjZlkwtOK33bf3vrgZc32fGd4rPuC5w_iiRaTzWjMLN289HmIdijhwxHaOxLkxWHaY.joZ3Zl5HkqVsFyXJSMtOVXD08O79oQGAFT6lT3qh-Nq19Ik-SIZDQ_HEgb3UmoTJOSHj5poHdr3HradDb1Xs5w.sc3', 'expires_in': '31536000'}}
2021-09-29 14:05:32 DEBUG (MainThread) [homeassistant.config_entries] Config entry 'FiberGateway GR241AG' for upnp integration not ready yet; Retrying in 80 seconds
2021-09-29 14:07:02 DEBUG (MainThread) [homeassistant.config_entries] Config entry 'FiberGateway GR241AG' for upnp integration not ready yet; Retrying in 80 seconds
2021-09-29 14:08:32 DEBUG (MainThread) [homeassistant.config_entries] Config entry 'FiberGateway GR241AG' for upnp integration not ready yet; Retrying in 80 seconds
2021-09-29 14:10:02 DEBUG (MainThread) [homeassistant.config_entries] Config entry 'FiberGateway GR241AG' for upnp integration not ready yet; Retrying in 80 seconds
2021-09-29 14:11:32 DEBUG (MainThread) [homeassistant.config_entries] Config entry 'FiberGateway GR241AG' for upnp integration not ready yet; Retrying in 80 seconds
2021-09-29 14:11:56 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] VERIFIER: CFdyXn7bM-GPe40Q_2iZ9vcCDL1x3a52Np0Z6Ipp4kHI1c_aYM1_z_~yWj2yrCXB
2021-09-29 14:11:56 ERROR (MainThread) [custom_components.daikin_residential.config_flow] Failed to retrieve Access Token: ('Failed to retrieve access token: %s', KeyError('code'))

**Comment by Limo888** [comment] 2021-09-29 13:22
I have the same problem. Maybe it is login with social media account? Apple in my case.

**Comment by jdserras** [comment] 2021-09-29 13:24
I get also this in log:

2021-09-29 14:16:40 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 213, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 202, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/usr/src/homeassistant/homeassistant/components/upnp/config_flow.py", line 290, in async_step_init
coordinator = self.hass.data[DOMAIN][self.config_entry.entry_id]
KeyError: 'e58a944d0546c7fea1d616bf0030d301'

**Comment by rospogrigio** [comment] 2021-09-29 13:26
> I have the same problem. Maybe it is login with social media account? Apple in my case.

I highly doubt but it's a very easy thing to test, just create an account using your email and see if it works with that. Anyway, as you can see the tokensaver and the HA integration are using the same code, so if the tokensaver works it has to be some tricky part that behaves differently in the two environments (I mean, command line and HA environment).

**Comment by jdserras** [comment] 2021-09-29 13:26
I am using connection through dynip service. Does it make any difference?

**Comment by rospogrigio** [comment] 2021-09-29 13:27
> I am using connection through dynip service. Does it make any difference?

I highly doubt...

**Comment by jdserras** [comment] 2021-09-29 13:49
This error originated from a custom integration.

Logger: custom_components.daikin_residential.config_flow
Source: custom_components/daikin_residential/config_flow.py:58
Integration: Daikin Residential Controller (documentation, issues)
First occurred: 14:48:15 (1 occurrences)
Last logged: 14:48:15

Failed to retrieve Access Token: ('Failed to retrieve access token: %s', KeyError('code'))

**Comment by rospogrigio** [comment] 2021-09-29 14:13
Again: the login part is working, and something goes wrong after that. 
Did you try to uncomment the `_LOGGER.debug` lines after the login part (line 383 and following) as I suggested earlier? It means to remove the "#" (and the following space in order to keep the correct indentation) to those lines and see what they log.

**Comment by jdserras** [comment] 2021-09-29 14:26
In configuration.yaml I have only this:

#### LOGGER
logger:
  default: error
  logs:
    #homeassistant.components.weather: debug
    #homeassistant.components.weather.ipma: debug
    #homeassistant.components.ipma: debug
    custom_components.daikin_residential.daikin_api: debug
    homeassistant.config: debug
    homeassistant.config_entries: debug

**Comment by rospogrigio** [comment] 2021-09-29 14:27
No, you have to edit the code in daikin_api.py .

**Comment by rospogrigio** [comment] 2021-09-29 16:08
I'm glad it's working now, even though it would be nice to understand what was the problem... anyway, please close the Issue if you believe it's ok now. Bye!

**Comment by jdserras** [comment] 2021-09-29 16:11
Thank you so much for your support

**Closed** 2021-09-29 16:12 UTC
