### ISSUE TITLE
fail to load with core update 2023.6.0 and 2023.6.1

### ISSUE THREAD

**Issue by domerich** [rospogrigio/daikin_residential#146] opened 2023-06-09 07:17 UTC
fail to load with core update 2023.6.0 and 2023.6.1
I am rolling back to 2023.5.4 as last known working

`Logger: homeassistant.config_entries
Source: custom_components/daikin_residential/daikin_api.py:54
Integration: Daikin Residential Controller ([documentation](https://github.com/rospogrigio/daikin_residential/), [issues](https://github.com/rospogrigio/daikin_residential/issues))
First occurred: 3:07:30 AM (3 occurrences)
Last logged: 3:08:37 AM

Error setting up entry Daikin for daikin_residential
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/__init__.py", line 84, in async_setup_entry
    daikin_api = DaikinApi(hass, entry)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/daikin_api.py", line 54, in __init__
    self.openIdClient = Client(client_id=self.openIdClientId, config=configuration)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/oic/__init__.py", line 354, in __init__
    self.settings = settings or OicClientSettings()
                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 96, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 51, in __init__
    self.client_cert = client_cert
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 73, in __setattr__
    raise SettingsException(
oic.utils.settings.SettingsException: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).`

![Bildschirmfoto vom 2023-06-09 03-02-18](https://github.com/rospogrigio/daikin_residential/assets/104911368/651942cd-9ddd-4049-a0f6-6f7cbc99f986)

**Comment by rospogrigio** [comment] 2023-06-09 07:58
This was fixed with latest release of the integration (2.3.1). Update and restart HA.
Please use the search function before posting, in the future.
Closing as duplicate of https://github.com/rospogrigio/daikin_residential/issues/140 .

**Closed by rospogrigio** 2023-06-09 07:58 UTC

**Comment by domerich** [comment] 2023-06-09 08:24
but how do I update? I don't see any update promt. I am stuck with 2.3.0

**Comment by rospogrigio** [comment] 2023-06-09 08:27
Go to HACS->Integrations, it should show you an update available. If it doesn't, search the integration and click on it, then go back and it should show that the update is available.

**Comment by domerich** [comment] 2023-06-09 08:34
this is really weird, I do not see the integration under hacks and even if I search it it does not show up. What can I do?

![image](https://github.com/rospogrigio/daikin_residential/assets/104911368/062802ac-c2de-44d7-8062-ac5433532ca1)

**Comment by rospogrigio** [comment] 2023-06-09 08:34
How did you install it then??

**Comment by domerich** [comment] 2023-06-09 08:36
Ah now I see, you have to add the integration by URL as it does not show up in the store

`Alternatively, you can install daikin_residential through HACS by adding this as a custom repository: press the three dots on the top right -> custom repositories -> type this URL in the Repository field and select Integration in the Category field.
`

now I can see it thanks!

**Comment by rospogrigio** [comment] 2023-06-09 08:36
I guess you installed it manually.
To install it using HACS, follow the instructions in the README:
**_"Alternatively, you can install daikin_residential through HACS by adding this as a custom repository: press the three dots on the top right -> custom repositories -> type this URL in the Repository field and select Integration in the Category field."_**

**Comment by domerich** [comment] 2023-06-09 08:39
yes is there a way to show it in HACS normally so I will not miss updates in the future?

**Comment by domerich** [comment] 2023-06-09 08:40
ah ok now it is showing in the list

**Comment by rospogrigio** [comment] 2023-06-09 09:48
Thank you @jwillemsen , merged #126 .
